- Birthdate: '1879-02-24'
  CalendarType: solar
  Email: ''
  Name: 爱因斯坦
- Birthdate: '1846-01-27'
  CalendarType: lunar
  Email: ''
  Name: 爱迪生
- Birthdate: '1879-12-28'
  CalendarType: solar
  Email: ''
  Name: lol