- Birthdate: '1879-2-24'
  Calendar: solar
  Email: ''
  Name: 爱因斯坦
- Birthdate: '1846-1-27'
  Calendar: lunar
  Email: ''
  Name: 爱迪生
- Birthdate: '1879-12-28'
  Calendar: solar
  Email: ''
  Name: lol