# 脚本机器人的名字
name: 'birthdayReminderBot'

# 触发条件
on:
  workflow_dispatch:
  watch:
    types: [ started ]
  schedule:
    - cron: '30 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 使用actions/checkout@v2获取仓库代码
      - name: 'Checkout'
        uses: actions/checkout@v2

      # 设置环境
      - name: Install Python
        run: |
            sudo apt update && \
            sudo apt install python3

      # 安装库
      - name: 'Install dependencies'
        run: pip3 install -r ./requirements.txt

      # 执行
      - name: 'run script'
        env:
          SENDER: ${{ secrets.SENDER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          RECEIVERS: ${{ secrets.RECEIVERS }}
          KEY: ${{ secrets.KEY }}
        run: python3 ./src/main.py
